# Generated by Django 5.0.6 on 2024-10-28 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apisend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='give_data',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^09\\d{9}$', 'شماره موبایل باید با 09 شروع شود و 11 رقم باشد.')]),
        ),
    ]
